####### 以下是FileLift相关配置 #######
io:
  github:
    swsk33:
      file-lift:
        core:
          # 使用本地文件系统储存上传的文件
          storage-method: "mongodb"
          # 上传文件最大限制为10240KB，即10MB
          # 不配置该选项表示不对文件大小做限制
          size-limit: 10240
          # 不允许同名文件上传覆盖
          override: false
          # 开启文件上传后自动命名功能
          auto-rename: true
          # 使用时间字符串对文件自动命名
          auto-rename-format: "time"
          # 允许上传的文件格式，这里表示允许jpg、png和无扩展名的文件上传
          # 不配置该选项表示允许任何格式文件上传
          allowed-formats:
            - "jpg"
            - "png"
            - "?"

# 配置MongoDB数据源
spring:
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "file_lift_test"
      username: "root"
      password: "dev-2333"
#      # 认证数据库，不配置则默认admin
#      authentication-database: "admin"
#      gridfs:
#        # 文件存储桶名称，不配置则默认fs
#        bucket: "my_fs"