####### 以下是FileLift相关配置 #######
io:
  github:
    swsk33:
      file-lift:
        core:
          # 使用MinIO储存上传的文件
          storage-method: "minio"
          # 上传文件最大限制为10240KB，即10MB
          # 不配置该选项表示不对文件大小做限制
          size-limit: 10240
          # 不允许同名文件上传覆盖
          override: false
          # 开启文件上传后自动命名功能
          auto-rename: true
          # 使用时间字符串对文件自动命名
          auto-rename-format: "simple_uuid"
          # 允许上传的文件格式，这里表示允许jpg、png和无扩展名的文件上传
          # 不配置该选项表示允许任何格式文件上传
          allowed-formats:
            - "jpg"
            - "png"
            - "?"
        # MinIO储存方案配置
        minio:
          # MinIO服务端地址和端口
          endpoint: "http://127.0.0.1:9000"
          # Access Key
          access-key: "SgVzkQOFzlvyuSaU96Yy"
          # Secret Key
          secret-key: "su5s6YtDK1oSGkp2pYptE6cogcn9vJErAadxZ7DF"
          # 存放文件的储存桶名称
          bucket-name: "op-test"